<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>



 <div class="container" id="op">
 
    
        <div class="col-md-5 col-md-offset-1">
   <div class="panel panel-default"  style="margin-right: -92px;margin-left: -162px;">
  <div class="panel-heading center">liste des produits</div>
  
  
 
  
  <table id="example" class="table table-striped " cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Nom_produit</th>
                <th>Prix</th>
                <th>Magasin</th>
                <th>categorie</th>
               
                <th>     <span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>
       
        <tbody>
        <tbody>
    <?php foreach($this->prodt as $p) : ?>
      <tr>
               <td><?php echo $this->escape($p->nom_produit);?></td>
               <td><?php echo $this->escape($p->prix);?></td>
               <td><?php 
               
              
               if($p->id_magasin=="1"){
               	echo "magasin_A";
               }else{
               	echo"magasin_B";
               }
               
               ?></td>
               <td><?php 
             
               	
               	  if($p->id_categorie=="1"){
               	echo "material_info";
               }else{
               	echo"vetements";
               }
               	
               	
               	?></td>
   
               <td>
            
 <a data-toggle="modal" data-target="#myModal" <?php $i=$p->id_produit; ?> <button class="btn btn-danger btn-sm" ><span class="glyphicon glyphicon-trash "></span></button></a>
  <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'modify', 'id'=>$p->id_produit));?>"> <button class="btn btn-default btn-sm"><span class="glyphicon glyphicon-edit "></span></button></a>             
                </td>
      </tr>
     <?php endforeach; ?>
  
 </tbody>
    </table>
  
   </div>
</div>

 	

    
        <div class="col-md-5 col-md-offset-1">

<div class="panel panel-default">
  <div class="panel-heading center">ajouter produit</div>
<div class="panel-body">

 <form class="form-horizontal" action="index" method="post">
  <div class="form-group">
  	<div class="row">
  		<label class="control-label col-sm-3 r" >Nom_Produit:</label>
  		 <div class="col-sm-9">
      
      <?php  echo $this->form->getElement('nom_produit')->setAttrib('class', 'form-control')->render();?>
     
     </div>
  		
  	</div>
     
  </div>
    <div class="form-group">
  	<div class="row">
  		<label class="control-label col-sm-3 r" >prix:</label>
  		 <div class="col-sm-9">
      
      <?php  echo $this->form->getElement('prix')->setAttrib('class', 'form-control')->render();?>
     
     </div>
  		
  	</div>
     
  </div>
    
  <div class="form-group">
  	<div class="row">
  		<label class="control-label col-sm-3 r" >magasin:</label>
  		 <div class="col-sm-9">
      
      <?php  
      
      echo $this->form->getElement('id_magasin')->setAttrib('class', 'form-control')->render();
	  
      ?>
     
     </div>
  		
  	</div>
     
  </div>
  <div class="form-group">
  	<div class="row">
  		<label class="control-label col-sm-3 r" >categorie:</label>
  		 <div class="col-sm-9">
      
      <?php  echo $this->form->getElement('id_categorie')->setAttrib('class', 'form-control')->render();?>
     
     </div>
  		
  	</div>
     
  </div>
  </div>
   <div class="panel-footer">
  <div class="form-group">
  	<div class="row">
  		
  		 <div class="col-sm-9">
        <input class="btn btn-default btn-md "  type="submit" id="ii">
      
     </div>
  		
  	</div>
     
  </div>
  </div>
  
</form>

</div>
</div><!--//rowprinc-->
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">delete produit</h4>
      </div>
      <div class="modal-body">
               <form action="<?php echo $this->url(array('action'=>'delete')); ?>"
method="post">
<div>
<input type="hidden" name="id" value="<?php echo $i; ?>" />

<div class="form-group">
 
  		<div class="row">
  		 <div class="col-md-3 col-md-offset-3">
  		 	
       <input   class="btn btn-danger btn-lg   "type="submit" name="del" value="Yes" />
    
     
  		</div>
  		<div class="col-md-6 ">
  			
  			  <input   class="btn btn-default btn-lg  "type="submit" name="del" value="No" />
  		</div>
  	</div>
     
  </div>
 
</div>
</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

  </div>
  
   

  
  
  
  
  <!--con-->
 